
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author MERTTUNAKURNAZ
 */
public class ChildMainUI extends javax.swing.JFrame {
    
    private static User currentUser;
    private DefaultTableModel exercisesTableModel;
    private ExerciseManagement exerciseManagement;
    /**
     * Creates new form ChildMainUI
     */
    public ChildMainUI(User currentUser) {
        initComponents();
        
        this.currentUser = currentUser;
        childMainHead.setText("    Merhaba, " + currentUser.getFullName() + " :)");
        
        exerciseManagement = new ExerciseManagement();
        exercisesTableModel = new CustomTableModel(exerciseTable).loadChildExercisesTableModel(exerciseManagement.getExercises());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ChildMainPanel = new javax.swing.JPanel();
        childMainHead = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        selectExerciseButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        exerciseTable = new javax.swing.JTable();
        modeTittleLabel = new javax.swing.JLabel();
        selectedModeLabel = new javax.swing.JLabel();
        questionNumLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(Toolkit.getDefaultToolkit().getScreenSize().width/5,Toolkit.getDefaultToolkit().getScreenSize().height/10);

        ChildMainPanel.setBackground(new java.awt.Color(5, 191, 219));
        ChildMainPanel.setPreferredSize(new java.awt.Dimension(800, 550));

        childMainHead.setFont(new java.awt.Font("Snap ITC", 0, 36)); // NOI18N
        childMainHead.setForeground(new java.awt.Color(238, 238, 238));
        childMainHead.setText("        Merhaba");
        childMainHead.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        logoutButton.setBackground(new java.awt.Color(0, 255, 202));
        logoutButton.setFont(new java.awt.Font("Snap ITC", 0, 14)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(238, 238, 238));
        logoutButton.setText("Çıkış Yap");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        selectExerciseButton.setBackground(new java.awt.Color(8, 131, 149));
        selectExerciseButton.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        selectExerciseButton.setForeground(new java.awt.Color(238, 238, 238));
        selectExerciseButton.setText("<html> <style> p {text-align: center;} </style> <body> <p>Egzersiz <br>Seç </p> </body> </html>");
        selectExerciseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectExerciseButtonActionPerformed(evt);
            }
        });

        jScrollPane3.setBackground(new java.awt.Color(10, 77, 104));
        jScrollPane3.setForeground(new java.awt.Color(238, 238, 238));
        jScrollPane3.setFont(new java.awt.Font("Snap ITC", 0, 12)); // NOI18N

        exerciseTable.setBackground(new java.awt.Color(10, 77, 104));
        exerciseTable.setFont(new java.awt.Font("Snap ITC", 0, 12)); // NOI18N
        exerciseTable.setForeground(new java.awt.Color(238, 238, 238));
        exerciseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Soru Sayısı", "Alıştırma Modu"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        exerciseTable.setColumnSelectionAllowed(false);
        exerciseTable.setFocusable(false);
        exerciseTable.setGridColor(new java.awt.Color(0, 0, 51));
        exerciseTable.setSelectionBackground(new java.awt.Color(8, 131, 149));
        exerciseTable.setSelectionForeground(new java.awt.Color(238, 238, 238));
        exerciseTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        exerciseTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        exerciseTable.setShowGrid(true);
        exerciseTable.getTableHeader().setReorderingAllowed(false);
        exerciseTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exerciseTableMousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(exerciseTable);
        exerciseTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (exerciseTable.getColumnModel().getColumnCount() > 0) {
            exerciseTable.getColumnModel().getColumn(0).setMinWidth(70);
            exerciseTable.getColumnModel().getColumn(0).setPreferredWidth(70);
            exerciseTable.getColumnModel().getColumn(0).setMaxWidth(70);
        }

        modeTittleLabel.setFont(new java.awt.Font("Snap ITC", 0, 36)); // NOI18N
        modeTittleLabel.setForeground(new java.awt.Color(238, 238, 238));
        modeTittleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        modeTittleLabel.setText("Seçilen Mod");

        selectedModeLabel.setFont(new java.awt.Font("Snap ITC", 0, 36)); // NOI18N
        selectedModeLabel.setForeground(new java.awt.Color(10, 77, 104));
        selectedModeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selectedModeLabel.setText("Mod Seçilmedi");

        questionNumLabel.setFont(new java.awt.Font("Snap ITC", 0, 36)); // NOI18N
        questionNumLabel.setForeground(new java.awt.Color(10, 77, 104));
        questionNumLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        questionNumLabel.setText(" ");

        javax.swing.GroupLayout ChildMainPanelLayout = new javax.swing.GroupLayout(ChildMainPanel);
        ChildMainPanel.setLayout(ChildMainPanelLayout);
        ChildMainPanelLayout.setHorizontalGroup(
            ChildMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(childMainHead, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ChildMainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ChildMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ChildMainPanelLayout.createSequentialGroup()
                        .addComponent(logoutButton)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ChildMainPanelLayout.createSequentialGroup()
                        .addGroup(ChildMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(ChildMainPanelLayout.createSequentialGroup()
                                .addGroup(ChildMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(modeTittleLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                    .addComponent(questionNumLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(selectExerciseButton))
                                .addGap(80, 80, 80))
                            .addGroup(ChildMainPanelLayout.createSequentialGroup()
                                .addComponent(selectedModeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))))
        );
        ChildMainPanelLayout.setVerticalGroup(
            ChildMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChildMainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ChildMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ChildMainPanelLayout.createSequentialGroup()
                        .addComponent(modeTittleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(selectedModeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(questionNumLabel)
                        .addGap(35, 35, 35)
                        .addComponent(selectExerciseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ChildMainPanelLayout.createSequentialGroup()
                        .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(childMainHead)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ChildMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ChildMainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed

        dispose();
        new LoginUI().setVisible(true);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void selectExerciseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectExerciseButtonActionPerformed

        int selectedRow = exerciseTable.getSelectedRow();
        
        if(selectedRow == -1){
            
            if(exerciseTable.getRowCount() == 0){
                
                JOptionPane.showMessageDialog(this, "Tanımlı Egzersiz Yok");
            }else{
                
                JOptionPane.showMessageDialog(this, "Lütfen Tablodan Egzerisiz Seçiniz");
            }
        }else{
            
            Exercise selectedExercise = exerciseManagement.getExercises().get(selectedRow);
            dispose();
            new GameScreenUI(currentUser, selectedExercise).setVisible(true);
        }
    }//GEN-LAST:event_selectExerciseButtonActionPerformed

    private void exerciseTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exerciseTableMousePressed
        
        //Tabloya tıklandığında seçili egzersizin özelliklerini ekrana yazdırma 
        
        int selectedRow = exerciseTable.getSelectedRow();

        selectedModeLabel.setText(exercisesTableModel.getValueAt(selectedRow, 1).toString());
        questionNumLabel.setText(exercisesTableModel.getValueAt(selectedRow, 0).toString() + " Soru");
    }//GEN-LAST:event_exerciseTableMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChildMainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChildMainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChildMainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChildMainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChildMainUI(currentUser).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ChildMainPanel;
    private javax.swing.JLabel childMainHead;
    private javax.swing.JTable exerciseTable;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel modeTittleLabel;
    private javax.swing.JLabel questionNumLabel;
    private javax.swing.JButton selectExerciseButton;
    private javax.swing.JLabel selectedModeLabel;
    // End of variables declaration//GEN-END:variables
}
