
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author MERTTUNAKURNAZ
 */
public class ExerciseOperationsUI extends javax.swing.JFrame {
    
    private static User currentUser;
    private DefaultTableModel exercisesTableModel;
    private ExerciseManagement exerciseManagement;
    /**
     * Creates new form AddExerciseUI
     */
    public ExerciseOperationsUI(User currentUser) {
        initComponents();
        
        this.currentUser = currentUser;
        
        exerciseManagement = new ExerciseManagement();
        exercisesTableModel = new CustomTableModel(exerciseTable).loadExercisesTableModel(exerciseManagement.getExercises());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exerciseOperationsPanel = new javax.swing.JPanel();
        addExercisePanel = new javax.swing.JPanel();
        addExerciseLabel = new javax.swing.JLabel();
        a1TF = new javax.swing.JTextField();
        ALabel = new javax.swing.JLabel();
        dash1 = new javax.swing.JLabel();
        exModeLabel = new javax.swing.JLabel();
        a2TF = new javax.swing.JTextField();
        BLabel = new javax.swing.JLabel();
        b1TF = new javax.swing.JTextField();
        dash2 = new javax.swing.JLabel();
        b2TF = new javax.swing.JTextField();
        eqMark = new javax.swing.JLabel();
        nTF = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        NLabel = new javax.swing.JLabel();
        deleteExercisePanel = new javax.swing.JPanel();
        delExerciseLabel = new javax.swing.JLabel();
        delExerciseButton = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        exerciseTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(Toolkit.getDefaultToolkit().getScreenSize().width/5,Toolkit.getDefaultToolkit().getScreenSize().height/10);

        exerciseOperationsPanel.setBackground(new java.awt.Color(8, 131, 149));
        exerciseOperationsPanel.setPreferredSize(new java.awt.Dimension(800, 550));

        addExercisePanel.setBackground(new java.awt.Color(5, 191, 219));
        addExercisePanel.setPreferredSize(new java.awt.Dimension(394, 272));

        addExerciseLabel.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        addExerciseLabel.setForeground(new java.awt.Color(238, 238, 238));
        addExerciseLabel.setText("      Egzersiz Ekle");
        addExerciseLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        a1TF.setBackground(new java.awt.Color(170, 119, 255));
        a1TF.setFont(new java.awt.Font("Snap ITC", 0, 36)); // NOI18N
        a1TF.setForeground(new java.awt.Color(238, 238, 238));
        a1TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a1TF.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a1TF.setPreferredSize(new java.awt.Dimension(70, 70));

        ALabel.setFont(new java.awt.Font("Snap ITC", 0, 36)); // NOI18N
        ALabel.setForeground(new java.awt.Color(238, 238, 238));
        ALabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ALabel.setText("A =");
        ALabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        dash1.setFont(new java.awt.Font("Snap ITC", 0, 36)); // NOI18N
        dash1.setForeground(new java.awt.Color(238, 238, 238));
        dash1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dash1.setText("-");

        exModeLabel.setFont(new java.awt.Font("Snap ITC", 0, 24)); // NOI18N
        exModeLabel.setForeground(new java.awt.Color(238, 238, 238));
        exModeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exModeLabel.setText("Alıştırma Modu -> A x B");

        a2TF.setBackground(new java.awt.Color(170, 119, 255));
        a2TF.setFont(new java.awt.Font("Snap ITC", 0, 36)); // NOI18N
        a2TF.setForeground(new java.awt.Color(238, 238, 238));
        a2TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a2TF.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        a2TF.setPreferredSize(new java.awt.Dimension(70, 70));

        BLabel.setFont(new java.awt.Font("Snap ITC", 0, 36)); // NOI18N
        BLabel.setForeground(new java.awt.Color(238, 238, 238));
        BLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BLabel.setText("B =");
        BLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        b1TF.setBackground(new java.awt.Color(170, 119, 255));
        b1TF.setFont(new java.awt.Font("Snap ITC", 0, 36)); // NOI18N
        b1TF.setForeground(new java.awt.Color(238, 238, 238));
        b1TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b1TF.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b1TF.setPreferredSize(new java.awt.Dimension(70, 70));

        dash2.setFont(new java.awt.Font("Snap ITC", 0, 36)); // NOI18N
        dash2.setForeground(new java.awt.Color(238, 238, 238));
        dash2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dash2.setText("-");

        b2TF.setBackground(new java.awt.Color(170, 119, 255));
        b2TF.setFont(new java.awt.Font("Snap ITC", 0, 36)); // NOI18N
        b2TF.setForeground(new java.awt.Color(238, 238, 238));
        b2TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b2TF.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b2TF.setPreferredSize(new java.awt.Dimension(70, 70));

        eqMark.setFont(new java.awt.Font("Snap ITC", 0, 36)); // NOI18N
        eqMark.setForeground(new java.awt.Color(238, 238, 238));
        eqMark.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eqMark.setText("=");
        eqMark.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        nTF.setBackground(new java.awt.Color(170, 119, 255));
        nTF.setFont(new java.awt.Font("Snap ITC", 0, 36)); // NOI18N
        nTF.setForeground(new java.awt.Color(238, 238, 238));
        nTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nTF.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nTF.setPreferredSize(new java.awt.Dimension(70, 70));

        addButton.setBackground(new java.awt.Color(8, 131, 149));
        addButton.setFont(new java.awt.Font("Snap ITC", 0, 14)); // NOI18N
        addButton.setForeground(new java.awt.Color(238, 238, 238));
        addButton.setText("Ekle");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        NLabel.setFont(new java.awt.Font("Snap ITC", 0, 24)); // NOI18N
        NLabel.setForeground(new java.awt.Color(238, 238, 238));
        NLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NLabel.setText("<html> <style> p {text-align: center;} </style> <body> <p>Soru <br>Sayısı </p> </body> </html>");
        NLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout addExercisePanelLayout = new javax.swing.GroupLayout(addExercisePanel);
        addExercisePanel.setLayout(addExercisePanelLayout);
        addExercisePanelLayout.setHorizontalGroup(
            addExercisePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addExerciseLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
            .addComponent(exModeLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(addExercisePanelLayout.createSequentialGroup()
                .addGroup(addExercisePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addExercisePanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(NLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(eqMark)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nTF, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addExercisePanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(addExercisePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(addExercisePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(addExercisePanelLayout.createSequentialGroup()
                                    .addComponent(BLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(b1TF, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(dash2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(b2TF, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(addExercisePanelLayout.createSequentialGroup()
                                    .addComponent(ALabel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(a1TF, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(dash1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(a2TF, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addExercisePanelLayout.setVerticalGroup(
            addExercisePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addExercisePanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(addExerciseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(exModeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(addExercisePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dash1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a1TF, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a2TF, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ALabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(addExercisePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dash2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b1TF, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b2TF, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(addExercisePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addExercisePanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(addExercisePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nTF, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eqMark))
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addExercisePanelLayout.createSequentialGroup()
                        .addComponent(NLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)))
                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );

        deleteExercisePanel.setBackground(new java.awt.Color(5, 191, 219));
        deleteExercisePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        delExerciseLabel.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        delExerciseLabel.setForeground(new java.awt.Color(238, 238, 238));
        delExerciseLabel.setText("      Egzersiz Sil");
        delExerciseLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        delExerciseButton.setBackground(new java.awt.Color(8, 131, 149));
        delExerciseButton.setFont(new java.awt.Font("Snap ITC", 0, 14)); // NOI18N
        delExerciseButton.setForeground(new java.awt.Color(238, 238, 238));
        delExerciseButton.setText("Sil");
        delExerciseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delExerciseButtonActionPerformed(evt);
            }
        });

        homeButton.setBackground(new java.awt.Color(0, 255, 202));
        homeButton.setFont(new java.awt.Font("Snap ITC", 0, 14)); // NOI18N
        homeButton.setForeground(new java.awt.Color(238, 238, 238));
        homeButton.setText("Ana Sayfa");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        jScrollPane3.setBackground(new java.awt.Color(10, 77, 104));
        jScrollPane3.setForeground(new java.awt.Color(238, 238, 238));

        exerciseTable.setBackground(new java.awt.Color(10, 77, 104));
        exerciseTable.setFont(new java.awt.Font("Snap ITC", 0, 12)); // NOI18N
        exerciseTable.setForeground(new java.awt.Color(238, 238, 238));
        exerciseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Mod"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        exerciseTable.setColumnSelectionAllowed(false);
        exerciseTable.setFocusable(false);
        exerciseTable.setGridColor(new java.awt.Color(0, 0, 51));
        exerciseTable.setSelectionBackground(new java.awt.Color(8, 131, 149));
        exerciseTable.setSelectionForeground(new java.awt.Color(238, 238, 238));
        exerciseTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        exerciseTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        exerciseTable.setShowGrid(true);
        exerciseTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(exerciseTable);
        exerciseTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (exerciseTable.getColumnModel().getColumnCount() > 0) {
            exerciseTable.getColumnModel().getColumn(0).setMinWidth(40);
            exerciseTable.getColumnModel().getColumn(0).setPreferredWidth(40);
            exerciseTable.getColumnModel().getColumn(0).setMaxWidth(50);
            exerciseTable.getColumnModel().getColumn(1).setMinWidth(150);
            exerciseTable.getColumnModel().getColumn(1).setPreferredWidth(150);
        }

        javax.swing.GroupLayout deleteExercisePanelLayout = new javax.swing.GroupLayout(deleteExercisePanel);
        deleteExercisePanel.setLayout(deleteExercisePanelLayout);
        deleteExercisePanelLayout.setHorizontalGroup(
            deleteExercisePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteExercisePanelLayout.createSequentialGroup()
                .addComponent(delExerciseLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(homeButton)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deleteExercisePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(deleteExercisePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(delExerciseButton, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE))
                .addGap(60, 60, 60))
        );
        deleteExercisePanelLayout.setVerticalGroup(
            deleteExercisePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteExercisePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(deleteExercisePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delExerciseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(delExerciseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout exerciseOperationsPanelLayout = new javax.swing.GroupLayout(exerciseOperationsPanel);
        exerciseOperationsPanel.setLayout(exerciseOperationsPanelLayout);
        exerciseOperationsPanelLayout.setHorizontalGroup(
            exerciseOperationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exerciseOperationsPanelLayout.createSequentialGroup()
                .addComponent(addExercisePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteExercisePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        exerciseOperationsPanelLayout.setVerticalGroup(
            exerciseOperationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deleteExercisePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(addExercisePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exerciseOperationsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exerciseOperationsPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void delExerciseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delExerciseButtonActionPerformed
        
        int selectedRow = exerciseTable.getSelectedRow();
        
        if(selectedRow == -1){
            
            if(exerciseTable.getRowCount() == 0){
                
                JOptionPane.showMessageDialog(this, "Silinecek Egzersiz Yok", "Hata!", JOptionPane.ERROR_MESSAGE);
            }else{
                
                JOptionPane.showMessageDialog(this, "Lütfen Tablodan Silinecek Egzersizi Seçiniz", "Hata!", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            
            //Silme onayı
            int option = JOptionPane.showConfirmDialog(this, "ID Numarası " + exercisesTableModel.getValueAt(selectedRow, 0) + " Olan Egzersizi Silmek İstiyor Musunuz?", "Onay", JOptionPane.YES_NO_OPTION);
            
            if(option == JOptionPane.YES_OPTION){
                
                if(exerciseManagement.delExercise((int)exerciseTable.getValueAt(selectedRow, 0))){

                    exercisesTableModel.removeRow(selectedRow);
                }else{

                    JOptionPane.showMessageDialog(this, "Silme İşlemi başarısız", "Hata!", JOptionPane.ERROR_MESSAGE);
                }    
            }
        }
    }//GEN-LAST:event_delExerciseButtonActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed

        dispose();
        new ParentMainUI(currentUser).setVisible(true);
    }//GEN-LAST:event_homeButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        
        String aMinString = a1TF.getText();
        String aMaxString = a2TF.getText();
        String bMinString = b1TF.getText();
        String bMaxString = b2TF.getText();
        String nString = nTF.getText();
        
        //Boş değer yoksa
        if(!aMinString.isEmpty() && !aMaxString.isEmpty() && !bMinString.isEmpty() && !bMaxString.isEmpty() && !nString.isEmpty()){
            
            int aMin = Integer.parseInt(aMinString);
            int aMax = Integer.parseInt(aMaxString);
            int bMin = Integer.parseInt(bMinString);
            int bMax = Integer.parseInt(bMaxString);
            int n = Integer.parseInt(nString);
            
            //Bütün değerler pozitifse
            if(aMin > 0 && aMax > 0 && bMin > 0 && bMax > 0 && n > 0){
                
                if(aMin < aMax){
                   
                    if(bMin < bMax){

                        int ID = exerciseManagement.addExercise(aMin, aMax, bMin, bMax, n);
                        JOptionPane.showMessageDialog(this, 
                                n + " sorudan oluşan "
                                + "[" + aMin + "-" + aMax + "]" + " x " + "[" + bMin + "-" + bMax + "]"
                                + " egzersizi başarıyla eklendi."
                        );
                        
                        
                        exercisesTableModel = CustomTableModel.addExerciseRow(exercisesTableModel, ID, exerciseManagement.getExercise(ID).getGameMode() + "/" + exerciseManagement.getExercise(ID).getQuestionNum() + " Soru");
                        
                        a1TF.setText("");
                        a2TF.setText("");
                        b1TF.setText("");
                        b2TF.setText("");
                        nTF.setText("");
                    }else{

                        JOptionPane.showMessageDialog(this, "B Aralığının Max Değeri Min Değerinden Küçük Olamaz", "Hata!", JOptionPane.ERROR_MESSAGE);
                    }
                }else{

                    JOptionPane.showMessageDialog(this, "A Aralığının Max Değeri Min Değerinden Küçük Olamaz", "Hata!", JOptionPane.ERROR_MESSAGE);
                }
            }else{
                
                JOptionPane.showMessageDialog(this, "Lütfen Gerekli Alanları Pozitif Değerlerle Doldurunuz", "Hata!", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            
            JOptionPane.showMessageDialog(this, "Lütfen Gerekli Bütün Alanları Doldurunuz", "Hata!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExerciseOperationsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExerciseOperationsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExerciseOperationsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExerciseOperationsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExerciseOperationsUI(currentUser).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ALabel;
    private javax.swing.JLabel BLabel;
    private javax.swing.JLabel NLabel;
    private javax.swing.JTextField a1TF;
    private javax.swing.JTextField a2TF;
    private javax.swing.JButton addButton;
    private javax.swing.JLabel addExerciseLabel;
    private javax.swing.JPanel addExercisePanel;
    private javax.swing.JTextField b1TF;
    private javax.swing.JTextField b2TF;
    private javax.swing.JLabel dash1;
    private javax.swing.JLabel dash2;
    private javax.swing.JButton delExerciseButton;
    private javax.swing.JLabel delExerciseLabel;
    private javax.swing.JPanel deleteExercisePanel;
    private javax.swing.JLabel eqMark;
    private javax.swing.JLabel exModeLabel;
    private javax.swing.JPanel exerciseOperationsPanel;
    private javax.swing.JTable exerciseTable;
    private javax.swing.JButton homeButton;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField nTF;
    // End of variables declaration//GEN-END:variables
}
