
import java.awt.Toolkit;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author MERTTUNAKURNAZ
 */
public class HighScoreUI extends javax.swing.JFrame {
    
    private static User currentUser;
    private static Exercise exercise;
    
    private DefaultTableModel highScoresTableModel;
    /**
     * Creates new form HighScoreUI
     */
    public HighScoreUI(User currentUser, Exercise exercise) {
        initComponents();
        
        this.currentUser = currentUser;
        this.exercise = exercise;
        
        highScoresTableModel = new CustomTableModel(highScoreTable).loadLeaderBoardTableModel(exercise.getHighScores());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HighScorePanel = new javax.swing.JPanel();
        backButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        highScoreTable = new javax.swing.JTable();
        scoreTableLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(Toolkit.getDefaultToolkit().getScreenSize().width/5,Toolkit.getDefaultToolkit().getScreenSize().height/10);

        HighScorePanel.setBackground(new java.awt.Color(5, 191, 219));
        HighScorePanel.setPreferredSize(new java.awt.Dimension(800, 550));
        HighScorePanel.setRequestFocusEnabled(false);
        HighScorePanel.setVerifyInputWhenFocusTarget(false);

        backButton.setBackground(new java.awt.Color(0, 255, 202));
        backButton.setFont(new java.awt.Font("Snap ITC", 0, 14)); // NOI18N
        backButton.setForeground(new java.awt.Color(238, 238, 238));
        backButton.setText("Geri Dön");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jScrollPane3.setBackground(new java.awt.Color(10, 77, 104));
        jScrollPane3.setForeground(new java.awt.Color(238, 238, 238));
        jScrollPane3.setFont(new java.awt.Font("Snap ITC", 0, 12)); // NOI18N

        highScoreTable.setBackground(new java.awt.Color(10, 77, 104));
        highScoreTable.setFont(new java.awt.Font("Snap ITC", 0, 12)); // NOI18N
        highScoreTable.setForeground(new java.awt.Color(238, 238, 238));
        highScoreTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kullanıcı Adı", "Toplam Skor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        highScoreTable.setFocusable(false);
        highScoreTable.setGridColor(new java.awt.Color(0, 0, 51));
        highScoreTable.setSelectionBackground(new java.awt.Color(8, 131, 149));
        highScoreTable.setSelectionForeground(new java.awt.Color(238, 238, 238));
        highScoreTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        highScoreTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        highScoreTable.setShowGrid(true);
        highScoreTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(highScoreTable);
        highScoreTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        scoreTableLabel.setFont(new java.awt.Font("Snap ITC", 0, 24)); // NOI18N
        scoreTableLabel.setForeground(new java.awt.Color(238, 238, 238));
        scoreTableLabel.setText("Yüksek Skor Tablosu");

        javax.swing.GroupLayout HighScorePanelLayout = new javax.swing.GroupLayout(HighScorePanel);
        HighScorePanel.setLayout(HighScorePanelLayout);
        HighScorePanelLayout.setHorizontalGroup(
            HighScorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HighScorePanelLayout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addGroup(HighScorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HighScorePanelLayout.createSequentialGroup()
                        .addComponent(scoreTableLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                        .addGap(119, 119, 119)
                        .addComponent(backButton))
                    .addGroup(HighScorePanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        HighScorePanelLayout.setVerticalGroup(
            HighScorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HighScorePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HighScorePanelLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(scoreTableLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HighScorePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 766, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HighScorePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed

        dispose();
        new GameScreenUI(currentUser, exercise).setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HighScoreUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HighScoreUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HighScoreUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HighScoreUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HighScoreUI(currentUser, exercise).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HighScorePanel;
    private javax.swing.JButton backButton;
    private javax.swing.JTable highScoreTable;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel scoreTableLabel;
    // End of variables declaration//GEN-END:variables
}
