
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author MERTTUNAKURNAZ
 */
public class ParentHighScoresUI extends javax.swing.JFrame {
    
    private static User currentUser;
    
    private ExerciseManagement exerciseManagement;
    
    private DefaultTableModel exercisesTableModel;
    private DefaultTableModel highScoresTableModel;
    /**
     * Creates new form ParentHighScoresUI
     */
    public ParentHighScoresUI(User currentUser) {
        initComponents();
        
        this.currentUser = currentUser;
        
        exerciseManagement = new ExerciseManagement();
        
        exercisesTableModel = new CustomTableModel(exerciseTable).loadExercisesTableModel(exerciseManagement.getExercises());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parentHighScorePanel = new javax.swing.JPanel();
        backButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        highScoreTable = new javax.swing.JTable();
        scoreTableLabel = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        exerciseTable = new javax.swing.JTable();
        exerciseTableLabel = new javax.swing.JLabel();
        showHighScoreButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(Toolkit.getDefaultToolkit().getScreenSize().width/5,Toolkit.getDefaultToolkit().getScreenSize().height/10);

        parentHighScorePanel.setBackground(new java.awt.Color(5, 191, 219));
        parentHighScorePanel.setPreferredSize(new java.awt.Dimension(800, 550));
        parentHighScorePanel.setRequestFocusEnabled(false);
        parentHighScorePanel.setVerifyInputWhenFocusTarget(false);

        backButton.setBackground(new java.awt.Color(0, 255, 202));
        backButton.setFont(new java.awt.Font("Snap ITC", 0, 14)); // NOI18N
        backButton.setForeground(new java.awt.Color(238, 238, 238));
        backButton.setText("Geri Dön");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jScrollPane3.setBackground(new java.awt.Color(10, 77, 104));
        jScrollPane3.setForeground(new java.awt.Color(238, 238, 238));
        jScrollPane3.setFont(new java.awt.Font("Snap ITC", 0, 12)); // NOI18N

        highScoreTable.setBackground(new java.awt.Color(10, 77, 104));
        highScoreTable.setFont(new java.awt.Font("Snap ITC", 0, 12)); // NOI18N
        highScoreTable.setForeground(new java.awt.Color(238, 238, 238));
        highScoreTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kullanıcı Adı", "Toplam Skor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        highScoreTable.setEnabled(false);
        highScoreTable.setFocusable(false);
        highScoreTable.setGridColor(new java.awt.Color(0, 0, 51));
        highScoreTable.setSelectionBackground(new java.awt.Color(8, 131, 149));
        highScoreTable.setSelectionForeground(new java.awt.Color(238, 238, 238));
        highScoreTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        highScoreTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        highScoreTable.setShowGrid(true);
        highScoreTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(highScoreTable);
        highScoreTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (highScoreTable.getColumnModel().getColumnCount() > 0) {
            highScoreTable.getColumnModel().getColumn(0).setMinWidth(150);
            highScoreTable.getColumnModel().getColumn(0).setPreferredWidth(150);
            highScoreTable.getColumnModel().getColumn(0).setMaxWidth(150);
        }

        scoreTableLabel.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        scoreTableLabel.setForeground(new java.awt.Color(238, 238, 238));
        scoreTableLabel.setText("Yüksek Skor Tablosu");

        jScrollPane4.setBackground(new java.awt.Color(10, 77, 104));
        jScrollPane4.setForeground(new java.awt.Color(238, 238, 238));

        exerciseTable.setBackground(new java.awt.Color(10, 77, 104));
        exerciseTable.setFont(new java.awt.Font("Snap ITC", 0, 12)); // NOI18N
        exerciseTable.setForeground(new java.awt.Color(238, 238, 238));
        exerciseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Mod"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        exerciseTable.setColumnSelectionAllowed(false);
        exerciseTable.setFocusable(false);
        exerciseTable.setGridColor(new java.awt.Color(0, 0, 51));
        exerciseTable.setSelectionBackground(new java.awt.Color(8, 131, 149));
        exerciseTable.setSelectionForeground(new java.awt.Color(238, 238, 238));
        exerciseTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        exerciseTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        exerciseTable.setShowGrid(true);
        exerciseTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(exerciseTable);
        exerciseTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (exerciseTable.getColumnModel().getColumnCount() > 0) {
            exerciseTable.getColumnModel().getColumn(0).setMinWidth(100);
            exerciseTable.getColumnModel().getColumn(0).setPreferredWidth(100);
            exerciseTable.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        exerciseTableLabel.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        exerciseTableLabel.setForeground(new java.awt.Color(238, 238, 238));
        exerciseTableLabel.setText("Egzersiz Tablosu");

        showHighScoreButton.setBackground(new java.awt.Color(8, 131, 149));
        showHighScoreButton.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        showHighScoreButton.setForeground(new java.awt.Color(238, 238, 238));
        showHighScoreButton.setText("Yüksek Skorları Göster");
        showHighScoreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showHighScoreButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout parentHighScorePanelLayout = new javax.swing.GroupLayout(parentHighScorePanel);
        parentHighScorePanel.setLayout(parentHighScorePanelLayout);
        parentHighScorePanelLayout.setHorizontalGroup(
            parentHighScorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, parentHighScorePanelLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(parentHighScorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(backButton)
                    .addGroup(parentHighScorePanelLayout.createSequentialGroup()
                        .addGroup(parentHighScorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(parentHighScorePanelLayout.createSequentialGroup()
                                .addGroup(parentHighScorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(parentHighScorePanelLayout.createSequentialGroup()
                                        .addComponent(exerciseTableLabel)
                                        .addGap(175, 175, 175))
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, parentHighScorePanelLayout.createSequentialGroup()
                                .addComponent(showHighScoreButton, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(parentHighScorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(scoreTableLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE))
                        .addGap(22, 22, 22)))
                .addContainerGap())
        );
        parentHighScorePanelLayout.setVerticalGroup(
            parentHighScorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parentHighScorePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(parentHighScorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(scoreTableLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exerciseTableLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(parentHighScorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(parentHighScorePanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(showHighScoreButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(parentHighScorePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(parentHighScorePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed

        dispose();
        new ParentMainUI(currentUser).setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void showHighScoreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showHighScoreButtonActionPerformed

        int selectedRow = exerciseTable.getSelectedRow();

        if(selectedRow == -1){

            if(exerciseTable.getRowCount() == 0){

                JOptionPane.showMessageDialog(this, "Ekli Egzersiz Yok", "Hata!", JOptionPane.ERROR_MESSAGE);
            }else{

                JOptionPane.showMessageDialog(this, "Lütfen Tablodan Egzersiz Seçiniz", "Hata!", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            
            Exercise selectedExercise = exerciseManagement.getExercises().get(selectedRow);
            if(selectedExercise.getHighScores().isEmpty()){
                
                JOptionPane.showMessageDialog(this, "Egzersiz daha önce yapılmamış", "Hata!", JOptionPane.ERROR_MESSAGE);
            }else{
                
                //Tablo ismini oyun modu yapma
                scoreTableLabel.setText(selectedExercise.getGameMode() + "/" + selectedExercise.getQuestionNum() + " Skor Tablosu");
                
                if(highScoresTableModel == null){   
                    
                    //Tablodan egzersiz seçilmediyse yeni model oluştur
                    highScoresTableModel = new CustomTableModel(highScoreTable).loadLeaderBoardTableModel(selectedExercise.getHighScores());
                }else{
                    
                    //Yeni egzersiz seçildiyse modeli güncelle
                    highScoresTableModel = CustomTableModel.changeLeaderBoardTableModel(highScoresTableModel, selectedExercise.getHighScores());
                }
            }
        }
    }//GEN-LAST:event_showHighScoreButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ParentHighScoresUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ParentHighScoresUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ParentHighScoresUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ParentHighScoresUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ParentHighScoresUI(currentUser).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTable exerciseTable;
    private javax.swing.JLabel exerciseTableLabel;
    private javax.swing.JTable highScoreTable;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel parentHighScorePanel;
    private javax.swing.JLabel scoreTableLabel;
    private javax.swing.JButton showHighScoreButton;
    // End of variables declaration//GEN-END:variables
}
