
import java.awt.Toolkit;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author MERTTUNAKURNAZ
 */
public class ParentMainUI extends javax.swing.JFrame {
    
    private static User currentUser;
    
    /**
     * Creates new form ParentMainUI
     */
    public ParentMainUI(User currentUser) {
        initComponents();
        
        this.currentUser = currentUser;
        
        parentMainHead.setText("    Merhaba, " + currentUser.getFullName() + " :)");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ParentMainPanel = new javax.swing.JPanel();
        showReportButton = new javax.swing.JButton();
        userOperationsButton = new javax.swing.JButton();
        addExerciseButton = new javax.swing.JButton();
        parentMainHead = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        highScoreButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(Toolkit.getDefaultToolkit().getScreenSize().width/5,Toolkit.getDefaultToolkit().getScreenSize().height/10);

        ParentMainPanel.setBackground(new java.awt.Color(5, 191, 219));

        showReportButton.setBackground(new java.awt.Color(8, 131, 149));
        showReportButton.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        showReportButton.setForeground(new java.awt.Color(238, 238, 238));
        showReportButton.setText("<html>\n<style>\np {text-align: center;}\n</style>\n<body>\n<p>Rapor\n<br>Göster\n</p>\n</body>\n</html>");
        showReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showReportButtonActionPerformed(evt);
            }
        });

        userOperationsButton.setBackground(new java.awt.Color(8, 131, 149));
        userOperationsButton.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        userOperationsButton.setForeground(new java.awt.Color(238, 238, 238));
        userOperationsButton.setText("<html>\n<style>\np {text-align: center;}\n</style>\n<body>\n<p>Kullanıcı\n<br>İşlemleri\n</p>\n</body>\n</html>");
        userOperationsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userOperationsButtonActionPerformed(evt);
            }
        });

        addExerciseButton.setBackground(new java.awt.Color(8, 131, 149));
        addExerciseButton.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        addExerciseButton.setForeground(new java.awt.Color(238, 238, 238));
        addExerciseButton.setText("<html>\n<style>\np {text-align: center;}\n</style>\n<body>\n<p>Alıştırma\n<br>İşlemleri\n</p>\n</body>\n</html>");
        addExerciseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addExerciseButtonActionPerformed(evt);
            }
        });

        parentMainHead.setFont(new java.awt.Font("Snap ITC", 0, 36)); // NOI18N
        parentMainHead.setForeground(new java.awt.Color(238, 238, 238));
        parentMainHead.setText("        Merhaba");
        parentMainHead.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        logoutButton.setBackground(new java.awt.Color(0, 255, 202));
        logoutButton.setFont(new java.awt.Font("Snap ITC", 0, 14)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(238, 238, 238));
        logoutButton.setText("Çıkış Yap");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        highScoreButton.setBackground(new java.awt.Color(8, 131, 149));
        highScoreButton.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        highScoreButton.setForeground(new java.awt.Color(238, 238, 238));
        highScoreButton.setText("<html> <style> p {text-align: center;} </style> <body> <p>Yüksek <br>Skorlar </p> </body> </html>");
        highScoreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                highScoreButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ParentMainPanelLayout = new javax.swing.GroupLayout(ParentMainPanel);
        ParentMainPanel.setLayout(ParentMainPanelLayout);
        ParentMainPanelLayout.setHorizontalGroup(
            ParentMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ParentMainPanelLayout.createSequentialGroup()
                .addContainerGap(686, Short.MAX_VALUE)
                .addComponent(logoutButton)
                .addContainerGap())
            .addComponent(parentMainHead, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ParentMainPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(userOperationsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(addExerciseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(highScoreButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(showReportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ParentMainPanelLayout.setVerticalGroup(
            ParentMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ParentMainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(parentMainHead)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                .addGroup(ParentMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showReportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addExerciseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userOperationsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(highScoreButton, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(135, 135, 135))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ParentMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ParentMainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userOperationsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userOperationsButtonActionPerformed
        
        dispose();
        new UserOperationsUI(currentUser).setVisible(true);
    }//GEN-LAST:event_userOperationsButtonActionPerformed

    private void addExerciseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addExerciseButtonActionPerformed
        
        dispose();
        new ExerciseOperationsUI(currentUser).setVisible(true);
    }//GEN-LAST:event_addExerciseButtonActionPerformed

    private void showReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showReportButtonActionPerformed
        
        dispose();
        new ReportsUI(currentUser).setVisible(true);
    }//GEN-LAST:event_showReportButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed

        dispose();
        new LoginUI().setVisible(true);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void highScoreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_highScoreButtonActionPerformed
        
        dispose();
        new ParentHighScoresUI(currentUser).setVisible(true);
    }//GEN-LAST:event_highScoreButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ParentMainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ParentMainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ParentMainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ParentMainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ParentMainUI(currentUser).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ParentMainPanel;
    private javax.swing.JButton addExerciseButton;
    private javax.swing.JButton highScoreButton;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel parentMainHead;
    private javax.swing.JButton showReportButton;
    private javax.swing.JButton userOperationsButton;
    // End of variables declaration//GEN-END:variables
}
