
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author MERTTUNAKURNAZ
 */
public class ReportsUI extends javax.swing.JFrame {
    
    private final static String reportFileName = "reports.csv"; 
    
    private static User currentUser;
    
    private ArrayList<String[]> mainReports;
    private ArrayList<ArrayList<String[]>> detailedReports;
    
    private DefaultTableModel mainReportTableModel;
    
    /**
     * Creates new form ReportsUI
     */
    public ReportsUI(User currentUser) {
        initComponents();
        
        this.currentUser = currentUser;
        
        mainReports = new ArrayList<String[]>();
        detailedReports = new ArrayList<ArrayList<String[]>>();
        
        ArrayList<String[]> fullReports = FileOperations.loadReportsFromFile(reportFileName);
        
        //Raporları iki parçaya ayırma
        for (String[] fullReport : fullReports) {
            
            //Raporların ana kısmını ayırma
            String[] tmpMainRepList = {fullReport[0], fullReport[1], fullReport[2], fullReport[3], fullReport[4], fullReport[5]};
            mainReports.add(tmpMainRepList);
            
            //Raporların sorularla ilgili kısmını ayaırma
            ArrayList<String[]> tmpDetailRepList = new ArrayList<String[]>();
            
            //Sorulan soruları ayırma
            String[] questionList = fullReport[6].split(":");
            for (int i = 0; i < questionList.length; i++) {
                
                //Sorulan soruların özelliklerini ayırma
                String[] questionPropertiesList = questionList[i].split("/");
                tmpDetailRepList.add(questionPropertiesList);
            }
            detailedReports.add(tmpDetailRepList);
        }
        
        mainReportTableModel = new CustomTableModel(reportsTable).loadMainReportTableModel(mainReports);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reportPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        reportsTable = new javax.swing.JTable();
        showDetailsButton = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        mainReportLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(Toolkit.getDefaultToolkit().getScreenSize().width/5,Toolkit.getDefaultToolkit().getScreenSize().height/10);

        reportPanel.setBackground(new java.awt.Color(5, 191, 219));
        reportPanel.setPreferredSize(new java.awt.Dimension(800, 550));
        reportPanel.setRequestFocusEnabled(false);
        reportPanel.setVerifyInputWhenFocusTarget(false);

        jScrollPane3.setBackground(new java.awt.Color(10, 77, 104));
        jScrollPane3.setForeground(new java.awt.Color(238, 238, 238));
        jScrollPane3.setFont(new java.awt.Font("Snap ITC", 0, 12)); // NOI18N

        reportsTable.setBackground(new java.awt.Color(10, 77, 104));
        reportsTable.setFont(new java.awt.Font("Snap ITC", 0, 12)); // NOI18N
        reportsTable.setForeground(new java.awt.Color(238, 238, 238));
        reportsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "İsim", "Mod", "Tarih", "Süre", "Doğruluk", "Zaman"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        reportsTable.setColumnSelectionAllowed(false);
        reportsTable.setFocusable(false);
        reportsTable.setGridColor(new java.awt.Color(0, 0, 51));
        reportsTable.setSelectionBackground(new java.awt.Color(8, 131, 149));
        reportsTable.setSelectionForeground(new java.awt.Color(238, 238, 238));
        reportsTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        reportsTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        reportsTable.setShowGrid(true);
        reportsTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(reportsTable);
        if (reportsTable.getColumnModel().getColumnCount() > 0) {
            reportsTable.getColumnModel().getColumn(0).setMinWidth(150);
            reportsTable.getColumnModel().getColumn(0).setMaxWidth(150);
            reportsTable.getColumnModel().getColumn(1).setMinWidth(175);
            reportsTable.getColumnModel().getColumn(1).setMaxWidth(175);
            reportsTable.getColumnModel().getColumn(2).setMinWidth(175);
            reportsTable.getColumnModel().getColumn(2).setMaxWidth(175);
            reportsTable.getColumnModel().getColumn(3).setMinWidth(100);
            reportsTable.getColumnModel().getColumn(3).setMaxWidth(100);
        }

        showDetailsButton.setBackground(new java.awt.Color(8, 131, 149));
        showDetailsButton.setFont(new java.awt.Font("Snap ITC", 0, 14)); // NOI18N
        showDetailsButton.setForeground(new java.awt.Color(238, 238, 238));
        showDetailsButton.setText("Detay Göster");
        showDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showDetailsButtonActionPerformed(evt);
            }
        });

        homeButton.setBackground(new java.awt.Color(0, 255, 202));
        homeButton.setFont(new java.awt.Font("Snap ITC", 0, 14)); // NOI18N
        homeButton.setForeground(new java.awt.Color(238, 238, 238));
        homeButton.setText("Ana Sayfa");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        mainReportLabel.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        mainReportLabel.setForeground(new java.awt.Color(238, 238, 238));
        mainReportLabel.setText("Raporlar");

        javax.swing.GroupLayout reportPanelLayout = new javax.swing.GroupLayout(reportPanel);
        reportPanel.setLayout(reportPanelLayout);
        reportPanelLayout.setHorizontalGroup(
            reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(reportPanelLayout.createSequentialGroup()
                        .addComponent(mainReportLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(homeButton)))
                .addContainerGap())
            .addGroup(reportPanelLayout.createSequentialGroup()
                .addGap(331, 331, 331)
                .addComponent(showDetailsButton)
                .addContainerGap(330, Short.MAX_VALUE))
        );
        reportPanelLayout.setVerticalGroup(
            reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(reportPanelLayout.createSequentialGroup()
                        .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reportPanelLayout.createSequentialGroup()
                        .addComponent(mainReportLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(showDetailsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(reportPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(reportPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showDetailsButtonActionPerformed

        int selectedRow = reportsTable.getSelectedRow();
        
        if(selectedRow == -1){
            
            if(reportsTable.getRowCount() == 0){
                
                JOptionPane.showMessageDialog(this, "Rapor Yok", "Hata!", JOptionPane.ERROR_MESSAGE);
            }else{
                
                JOptionPane.showMessageDialog(this, "Lütfen Tablodan Rapor Seçiniz", "Hata!", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            
            dispose();
            new DetailedReportUI(currentUser, detailedReports.get(selectedRow)).setVisible(true);
        }
    }//GEN-LAST:event_showDetailsButtonActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        
        dispose();
        new ParentMainUI(currentUser).setVisible(true);
    }//GEN-LAST:event_homeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportsUI(currentUser).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton homeButton;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel mainReportLabel;
    private javax.swing.JPanel reportPanel;
    private javax.swing.JTable reportsTable;
    private javax.swing.JButton showDetailsButton;
    // End of variables declaration//GEN-END:variables
}
